### ISSUE TITLE
Json Viewer incompatible with build 203.* 

### ISSUE THREAD

**Issue by deeppunster** [MaaxGr/intellij-jsonviewer#1]
Apparently JetBrains has changed their api for plugins again.  I'm getting this message from PyCharm:

    `Incompatible: requires IDE build 202.* or older`

with PyCharm 

> PyCharm 2020.3.1 (Professional Edition)
> Build #PY-203.6682.86, built on December 21, 2020

I have no idea how trivial or non-trivial this is.  If you are no longer willing to jump through JetBrains's hoops, please reject this issue so I will know to switch to other, less convenient, software to accomplish what this tool can do.  Thanks!

**Comment by MaaxGr** [comment]
Hey. I will look into the issue and get back to you later. Thanks for reporting the api change. :)

**Comment by MaaxGr** [comment]
Hey Travis,

i just uploaded a new version of the plugin (1.0.7). The plugin will be available after JetBrains approval.

If you want to use the new version now, you can download the plugin and Choose "Install Plugin from Disk"
https://plugins.jetbrains.com/plugin/download?rel=true&updateId=106247

I'm going to close this ticket, when the update is publicly avaible.
Feel free to reach me if you have any suggestion, ideas or problems!

**Comment by MaaxGr** [comment]
New Version is now publicly available: https://plugins.jetbrains.com/plugin/14149-json-viewer/versions
