### ISSUE TITLE
Json Viewer incompatible with build 203.* or older

### ISSUE THREAD

**Issue by apgapg** [MaaxGr/intellij-jsonviewer#2]
v1.0.7

Recently i updated my IntelliJ and above errors pops in.
Looking forward to resolution

**Comment by MaaxGr** [comment]
Hey apgapg,

thanks for your issues. :)

I have just created a new version for IntelliJ 2021.1 version.
I'm sure jetbrains will approve the update in the next days.

Feel free to beta-test: https://plugins.jetbrains.com/plugin/14149-json-viewer/versions/stable/117123

**Comment by apgapg** [comment]
Thanks for the update and quick response.

**Comment by apgapg** [comment]
It worked fine. Thanks for the link.

**Comment by MaaxGr** [comment]
Hey @apgapg,

Jetbrains was really fast and approved the update already.

Update should also be downloadable via the IDE now.
https://plugins.jetbrains.com/plugin/14149-json-viewer/versions

// Issue closed
