### ISSUE TITLE
Cannot close the search window after ctrl+F  again

### ISSUE THREAD

**Issue by gerryhjs** [MaaxGr/intellij-jsonviewer#3]

**Comment by gerryhjs** [comment]
There is no way to close the search windows.Maybe add a close button on the search tab.

**Comment by MaaxGr** [comment]
Hey gerryhjs,

good idea! Do you want to contribute it by yourself? Feel free to do so. (Because you forked)

I'm happy to accept your pull request :)

**Comment by gerryhjs** [comment]
I hava a idea. I just found use ctrl+r can turn out the replace windows by idea own one and it can be closed. Is it possible to remove the ctrl+f find windows and use the idea original find windows instead?

**Comment by gerryhjs** [comment]
![jsonViewer](https://user-images.githubusercontent.com/45413498/118452206-84d41b00-b728-11eb-876d-9ac4fcc9a374.png)

**Comment by gerryhjs** [comment]
Hey MaaxGr, I am not a kotlin programmer so I cannot help you contribute to modify the code.
I guess is better to remove the compoment defined in Msearch.kt and use the search compoment by idea own.  It will be able to close ,or use the search filter function in idea such as regex or words find.

**Comment by gerryhjs** [comment]
When I use the ctrl+r to call up the replace windows of idea , and use the ctrl+f again , it works find like this:
![jsonviewer2](https://user-images.githubusercontent.com/45413498/118453447-d03af900-b729-11eb-96ba-bab9c542a4de.png)

**Comment by MaaxGr** [comment]
Last time i tryed, i realized, that the original idea-search component is not responsive. 
So when the JSON Viewer Window is very small, essentials parts of the searchbar where cut out.
Can you confirm that @gerryhjs? I think this was the only reason i implemented the search by myself

**Comment by gerryhjs** [comment]
@MaaxGr I tried the original one seems works fines here in idea-IU 2020.3. Not responsive doesn't happened in my ide.

**Comment by MaaxGr** [comment]
Okay. Thanks for testing. I will try to patch that 😄👍🏻

**Comment by gerryhjs** [comment]
Thanks for your patching. I will closed the issue :) @MaaxGr

**Comment by MaaxGr** [comment]
I mean this with lack of responsiveness (IDEA 2021.1):
<img width="294" alt="Bildschirmfoto 2021-05-17 um 13 49 49" src="https://user-images.githubusercontent.com/43404580/118484224-484bf380-b717-11eb-9b83-721f548584d0.png">

So just using the native search still doesn't work for this plugin.
The default hotkey for leaving the search was intended to be "esc" (escape)
It seems that this hotkey doesn't work on all operating systems (e.g. MacOS)
=> With the next update (v1.0.9) you can press ctrl+f inside the search box to close the search window again

**Comment by gerryhjs** [comment]
Well fine.I didnt try to change the viewer so small. This may because the idea search windows doesn't suit for small windows.

**Comment by gerryhjs** [comment]
@MaaxGr  Maybe you also need to disable the search or replace windows in Json viewer to avoid they come out on the viewer if possible.
