### ISSUE TITLE
Version bump to 2021.3 currently incompatible

### ISSUE THREAD

**Issue by AddictArts** [MaaxGr/intellij-jsonviewer#4]
Hopefully just a version bump will do it. Thanks

**Comment by MaaxGr** [comment]
Hi @AddictArts,

i just bump the version und uploaded it to the jetbrains marketplace.
https://plugins.jetbrains.com/plugin/14149-json-viewer/versions/stable/149147

It should be available in the idea in one or two days.
I will leave this issue open until it is finally released.

Thanks for using the plugin. Have a nice day!

Max

**Comment by MaaxGr** [comment]
Hey @AddictArts. The Version should be live, so i will close this issue now. Feel free to reopen or create another, if you have any problems with this plugin and IntelliJ 2021.3

Have a nice day!
Max
